import React from 'react';
import { Typography } from '@mui/joy';
import { CssVarsProvider } from "@mui/joy/styles";
import Stack from "@mui/joy/Stack";

const TermsAndConditions: React.FC = () => {
  return (
<CssVarsProvider>
  <Stack
    sx={{
      backgroundColor: 'background.surface',
      px: { xs: 2, md: 4 },
      py: 2,
      borderBottom: '1px solid',
      borderColor: 'divider',
    }}
  >
    <div>
      <Typography level="h2">Terms and Conditions</Typography>
      <Typography >
        Plogi (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Plogi.
        This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Plogi. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
      </Typography>

      <Typography level="h2">Definitions and key terms</Typography>
      <Typography>
        To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are
        referenced, are strictly defined as: <br />
        ● Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your
        browser, provide analytics, remember information about you such as your language preference or login
        information. <br />
        ● Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Plogi, that is responsible
        for your information under this Privacy Policy. <br />
        ● Country: where Plogi or the owners/founders of Plogi are based, in this case is ???????? <br />
        ● Customer: refers to the company, organization or person that signs up to use the Plogi Service to manage the
        relationships with your consumers or service users. <br />
        ● Device: any internet connected device such as a phone, tablet, computer or any other device that can be used
        to visit Plogi and use the services. <br />
        ● IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP)
        address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify
        the location from which a device is connecting to the Internet. <br />
        ● Personnel: refers to those individuals who are employed by Plogi or are under contract to perform a service on
        behalf of one of the parties. <br />
        ● Personal Data: any information that directly, indirectly, or in connection with other information — including
        a personal identification number — allows for the identification or identifiability of a natural person. <br />
        ● Service: refers to the service provided by Plogi as described in the relative terms (if available) and on this
        platform. <br />
        ● Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others
        who provide our content or whose products or services we think may interest you. <br />
        ● Website: Plogi’s site, which can be accessed via this URL: plogi.app <br />
        ● You: a person or entity that is registered with Plogi to use the Services. <br />

      </Typography>
      <Typography level="h2">What Information Do We Collect?</Typography>
      <Typography>
        We collect information from you when you visit our website, register on our site, place an order, subscribe to
        our newsletter, respond to a survey or fill out a form. <br />
        ● Name / Username <br />
        ● Phone Numbers <br />
        ● Email Addresses <br />
        ● Job Titles <br />
        ● Password <br />
      </Typography>
      <Typography level="h2">When does Plogi use end user information from third parties?</Typography>
      <Typography>
        Plogi will collect End User Data necessary to provide the Plogi services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
      </Typography>

      <Typography level="h2">When does Plogi use customer information from third parties?</Typography>
      <Typography>
        We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Plogi customer, we receive information from a third party that provides automated fraud detection services to Plogi. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.

      </Typography>

      <Typography level="h2">Do we share the information we collect with third parties?</Typography>
      <Typography>
        We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
        We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
        We may share portions of our log file data, including IP addresses, for analytics purposes with third parties
        page 2/10
        such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers.
        We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
      </Typography>


      <Typography level="h2">Where and when is information collected from customers and end users?</Typography>
      <Typography>
        Plogi will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
      </Typography>


      <Typography level="h2">How Do We Use The Information We Collect?</Typography>
      <Typography>
        Any of the information we collect from you may be used in one of the following ways:<br />
        ● To personalize your experience (your information helps us to better respond to your individual needs) <br />
        ● To improve our website (we continually strive to improve our website offerings based on the information and
        feedback we receive from you) <br />
        ● To improve customer service (your information helps us to more effectively respond to your customer service
        requests and support needs) <br />
        ● To process transactions <br />
        ● To administer a contest, promotion, survey or other site feature <br />
        ● To send periodic emails <br />
      </Typography>
      <Typography level="h2">Contact Us</Typography>
      <Typography>
        Don't hesitate to contact us if you have any questions. <br/>
        ● Via Email: plogi.info@gmail.com <br/>
        ● Via Phone Number: 009665402602211 <br/>
      </Typography>
    </div>
  </Stack>
</CssVarsProvider>
  );
};

export default TermsAndConditions;
